"""Wire-format regressions and bounded, explicitly marshaled helper checks.

The byte-pointer calls below are test-only ABI setup, not public Param support.
All binaries come from the session's pinned-container corpus build.
"""

import random
import struct
from collections import Counter
from pathlib import Path

import capstone
import pytest
from capstone.x86 import X86_OP_IMM
from elftools.elf.elffile import ELFFile

from reschema.corpus.generate import _symtab
from reschema.disasm.analyze import function_insns
from reschema.driver.calling import SENTINEL, _boot_vm, batch_call_original
from reschema.driver.spec import Param
from reschema.exec.recorder import record
from reschema.validate.program import _pkfmt_grammar_packet


def _packet(*records):
    return (
        b"\xb1\x5a\x03"
        + bytes([len(records)])
        + b"".join(
            bytes([tag]) + len(payload).to_bytes(2, "little") + payload
            for tag, payload in records
        )
    )


def _shape(packet):
    """Independent decoder used to check actual generated bytes."""
    if packet[:2] != b"\xb1\x5a":
        return "magic"
    if packet[2] not in (2, 3, 4):
        return "version"
    rest = packet[4:]
    for _ in range(packet[3]):
        if len(rest) < 3:
            return "header"
        length = int.from_bytes(rest[1:3], "little")
        rest = rest[3:]
        if len(rest) < length:
            return "payload"
        rest = rest[length:]
    return "extra" if rest else "valid"


def test_pkfmt_grammar_reaches_valid_and_truncated_payloads():
    rng = random.Random(125)
    draws = [_pkfmt_grammar_packet(rng) for _ in range(1000)]
    classes = Counter(map(_shape, draws))
    assert classes["valid"] > 100
    # Valid magic/version ensure these reach the parser's truncation branch.
    assert classes["payload"] > 20, classes
    assert classes["magic"] > 20 and classes["version"] > 20
    assert max(map(len, draws)) < 4096
    again = random.Random(125)
    assert draws == [_pkfmt_grammar_packet(again) for _ in draws]


MATRIX = [(cc, opt) for cc in ("gcc", "clang") for opt in ("-O0", "-O1", "-O2")]


def _slot(corpus, cc, opt, stripped=False):
    return next(
        x
        for x in corpus
        if (x["seed"], x["compiler"], x["opt"], x["stripped"])
        == ("pkfmt", cc, opt, stripped)
    )


@pytest.mark.parametrize("cc,opt", MATRIX)
@pytest.mark.parametrize("stripped", [False, True])
def test_pkfmt_public_surface_and_program(built_corpus, cc, opt, stripped):
    slot = _slot(built_corpus, cc, opt, stripped)
    assert set(slot["functions"]) == {"pk_version_ok"}
    cases = [{"v": v} for v in (-2147483648, 1, 2, 3, 4, 5, 2147483647)]
    outs = batch_call_original(
        slot["binary"],
        slot["functions"]["pk_version_ok"]["addr"],
        [Param("v", "i32")],
        cases,
    )
    assert [o["ret"] for o in outs] == [0, 0, 32, 48, 64, 0, 0]
    mode = "fresh-vm-fallback" if stripped else "batched-snapshot"
    assert all(o["exit_code"] == 0 and o["batch_mode"] == mode for o in outs)
    for packet, rc, stdout in (
        (
            _packet((0x20, b"\x04"), (0x30, b"\x01")),
            0,
            b"v=48 sum=5 xor-lit=2 fnv=39c57c46\n",
        ),
        (b"\xb1\x5a\x03\x01", 2, b"truncate\n"),
    ):
        got = record(slot["binary"], [], packet)
        assert (got["exit_code"], bytes.fromhex(got["stdout"])) == (rc, stdout)


def _checksum(packet):
    h = 2166136261
    for byte in packet[4:]:
        h = ((h ^ byte) * 16777619) & 0xFFFFFFFF
    return h


def _extract_cases():
    # Exact expected values, including the unsigned xor seed and opaque tags.
    yield _packet(), 0x20, 0, 0
    yield _packet(), 0x30, 0xA0A0A0A0, 0
    yield _packet((0x20, b"\x05")), 0x20, 6, 0
    yield _packet((0x30, b"\x05")), 0x30, 0xA0A0A0A6, 0
    yield _packet((0x99, b"opaque"), (0x20, b"")), 0x20, 0, 0
    yield _packet(), 0x99, 0, 4
    yield b"", 0x20, 0, 1
    yield b"\xb1\x5a\x03\x01", 0x20, 0, 2  # missing record
    yield _packet() + b"\x20", 0x20, 0, 2  # partial extra header
    yield _packet() + b"\x20\x01\x00\x05", 0x20, 0, 2  # extra record
    yield b"\xb1\x5a\x03\x01\x20\x01", 0x20, 0, 2
    yield _packet((0x20, b"\x05"))[:-1], 0x20, 0, 2
    yield _packet((0x20, bytes(1024))), 0x20, 1048576, 0
    yield _packet((0x20, bytes(1025))), 0x20, 0, 2
    # Largest accepted packet: 4-byte header + 4 record headers + 4080 data.
    yield _packet(*[(0x20, bytes(1020))] * 4), 0x20, 4161600, 0


@pytest.mark.parametrize("cc,opt", MATRIX)
def test_pkfmt_helpers_leaf_bounds_and_snapshot_isolation(built_corpus, cc, opt):
    binary = _slot(built_corpus, cc, opt)["binary"]
    symbols = _symtab(Path(binary))
    for name in ("pk_version_ok", "pk_extract", "pk_checksum"):
        addr, size = symbols[name]
        insns = function_insns(binary, addr, size)
        assert insns and sum(i.size for i in insns) == size
        for ins in insns:
            assert ins.mnemonic not in ("syscall", "sysenter", "int")
            assert not ins.group(capstone.CS_GRP_CALL), (name, ins.mnemonic)
            if ins.group(capstone.CS_GRP_JUMP):
                assert ins.operands[0].type == X86_OP_IMM
                assert addr <= ins.operands[0].imm < addr + size
    with open(binary, "rb") as f:
        symtab = ELFFile(f).get_section_by_name(".symtab")
        errno = next(
            int(s["st_value"]) for s in symtab.iter_symbols() if s.name == "pk_errno"
        )

    def boot():
        ql = _boot_vm(binary)
        ql.mem.map(0x2000000, 4096)
        return ql

    def invoke(ql, name, packet, tag=0x20, n=None):
        # Buffer ends at an unmapped page: an overread becomes an emulation fault.
        ptr = 0x2001000 - len(packet)
        if packet:
            ql.mem.write(ptr, packet)
        ql.mem.write(errno, struct.pack("<i", 77))
        regs = ql.arch.regs
        regs.rdi = ptr if n is None else 0  # invalid n must reject before dereference
        regs.rsi = (len(packet) if n is None else n) & 0xFFFFFFFF
        regs.rdx = tag
        top = ql.loader.stack_address
        regs.rsp = top - ((top - 8) % 16)
        ql.stack_write(0, SENTINEL)
        ql.run(begin=symbols[name][0], end=SENTINEL, timeout=300_000)
        assert regs.rip == SENTINEL
        if packet:
            assert bytes(ql.mem.read(ptr, len(packet))) == packet
        return regs.rax & 0xFFFFFFFF, int.from_bytes(ql.mem.read(errno, 4), "little")

    cases = list(_extract_cases())
    ql = boot()
    try:
        snap = ql.save()
        # Reverse order catches history dependence; poisoned errno must reset.
        for packet, tag, value, error in cases + list(reversed(cases)):
            ql.restore(snap)
            assert bytes(ql.mem.read(errno, 4)) == bytes(4)
            assert invoke(ql, "pk_extract", packet, tag) == (value, error)
        for packet in (_packet(), _packet((0x20, b"\x00\xff")), cases[-1][0]):
            ql.restore(snap)
            assert invoke(ql, "pk_checksum", packet) == (_checksum(packet), 0)
        for name in ("pk_extract", "pk_checksum"):
            for n in (-2147483648, -1, 0, 3, 4097, 2147483647):
                ql.restore(snap)
                assert invoke(ql, name, b"", n=n) == (0, 1)
    finally:
        ql._reschema_rf.cleanup()
    # A fresh-VM control for success, unsigned return, and malformed input.
    for packet, tag, value, error in (cases[2], cases[3], cases[7]):
        fresh = boot()
        try:
            assert invoke(fresh, "pk_extract", packet, tag) == (value, error)
        finally:
            fresh._reschema_rf.cleanup()


@pytest.mark.parametrize("suffix", [b"\x20", b"\x20\x01", b"\x20\x01\x00\x05"])
def test_pkfmt_program_rejects_extra_records(built_corpus, suffix):
    got = record(_slot(built_corpus, "gcc", "-O2")["binary"], [], _packet() + suffix)
    assert (got["exit_code"], bytes.fromhex(got["stdout"])) == (2, b"truncate\n")


def test_pkfmt_program_rejects_input_beyond_packet_limit(built_corpus):
    packet = _packet(*[(0x20, bytes(1020))] * 4)
    assert len(packet) == 4096
    got = record(_slot(built_corpus, "gcc", "-O2")["binary"], [], packet + b"\x00")
    assert (got["exit_code"], bytes.fromhex(got["stdout"])) == (2, b"truncate\n")
